// Mock Initial Seed Database for Bengkel Stelle System

export const INITIAL_USERS = [
  {
    id: 1,
    name: 'Budi Santoso',
    email: 'budi@stelle.id',
    phone_number: '081234567890',
    role: 'customer',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 2,
    name: 'Agus Pratama',
    email: 'agus.mechanic@stelle.id',
    phone_number: '081987654321',
    role: 'mechanic',
    specialty: 'Senior Engine Specialist',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 3,
    name: 'Siti Rahmawati',
    email: 'siti.admin@stelle.id',
    phone_number: '085712345678',
    role: 'admin',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 4,
    name: 'Hendra Wijaya',
    email: 'owner@stelle.id',
    phone_number: '081122334455',
    role: 'owner',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
  },
];

export const INITIAL_VEHICLES = [
  {
    id: 101,
    user_id: 1,
    license_plate: 'B 1234 XYZ',
    brand: 'Toyota',
    model: 'Avanza Veloz 1.5 AT',
    manufacture_year: 2021,
    engine_capacity: 1500,
    type: 'Mobil',
  },
  {
    id: 102,
    user_id: 1,
    license_plate: 'B 5678 EFG',
    brand: 'Honda',
    model: 'Vario 150 eSP',
    manufacture_year: 2022,
    engine_capacity: 150,
    type: 'Motor',
  },
];

export const INITIAL_SERVICES = [
  {
    id: 1,
    code: 'SRV-001',
    name: 'Servis Berkala & Ganti Oli Mesin',
    description: 'Pemeriksaan 21 titik komponen, tune up standar, dan penggantian oli filter.',
    price: 150000,
    estimated_duration_minutes: 45,
    category: 'Rutinkan',
    icon: 'Wrench',
  },
  {
    id: 2,
    code: 'SRV-002',
    name: 'Tune Up Injector & Carbon Clean',
    description: 'Pembersihan ruang bakar mesin dari kerak karbon untuk mengembalikan performa & efisiensi BBM.',
    price: 250000,
    estimated_duration_minutes: 60,
    category: 'Performa',
    icon: 'Zap',
  },
  {
    id: 3,
    code: 'SRV-003',
    name: 'Servis Rem Depan & Belakang',
    description: 'Pembersihan caliper, penggantian minyak rem, & inspeksi ketebalan kampas rem.',
    price: 120000,
    estimated_duration_minutes: 40,
    category: 'Keselamatan',
    icon: 'ShieldAlert',
  },
  {
    id: 4,
    code: 'SRV-004',
    name: 'Scanning Diagnostik Engine ECU',
    description: 'Deteksi kode error sensor mobil menggunakan OBD-II scanner canggih.',
    price: 100000,
    estimated_duration_minutes: 30,
    category: 'Diagnostik',
    icon: 'Cpu',
  },
  {
    id: 5,
    code: 'SRV-005',
    name: 'Overhaul Mesin Total',
    description: 'Turun mesin total, skir klep, penggantian packing cylinder head & paking carter.',
    price: 1800000,
    estimated_duration_minutes: 480,
    category: 'Berat',
    icon: 'Settings',
  },
];

export const INITIAL_SPAREPARTS = [
  {
    id: 1,
    part_code: 'PRT-OLI-001',
    name: 'Oli Mesin Shell Helix Ultra 5W-40 (1L)',
    category: 'Pelumas',
    stock: 24,
    min_stock: 5,
    purchase_price: 120000,
    selling_price: 165000,
  },
  {
    id: 2,
    part_code: 'PRT-FIL-002',
    name: 'Filter Oli Original Toyota Avanza',
    category: 'Filter',
    stock: 15,
    min_stock: 5,
    purchase_price: 32000,
    selling_price: 45000,
  },
  {
    id: 3,
    part_code: 'PRT-REM-003',
    name: 'Kampas Rem Depan Bendix Metal King Avanza',
    category: 'Pengereman',
    stock: 3, // LOW STOCK TRIGGER
    min_stock: 5,
    purchase_price: 180000,
    selling_price: 260000,
  },
  {
    id: 4,
    part_code: 'PRT-BUS-004',
    name: 'Busi NGK Iridium IX (Set 4 Busi)',
    category: 'Pengapian',
    stock: 12,
    min_stock: 4,
    purchase_price: 280000,
    selling_price: 380000,
  },
  {
    id: 5,
    part_code: 'PRT-AIR-005',
    name: 'Filter Udara Denso Replacement Avanza',
    category: 'Filter',
    stock: 2, // LOW STOCK TRIGGER
    min_stock: 5,
    purchase_price: 65000,
    selling_price: 95000,
  },
];

export const INITIAL_BOOKINGS = [
  {
    id: 1001,
    booking_code: 'BK-20260722-001',
    user_id: 1,
    user_name: 'Budi Santoso',
    user_phone: '081234567890',
    vehicle_id: 101,
    license_plate: 'B 1234 XYZ',
    vehicle_model: 'Toyota Avanza Veloz 1.5 AT',
    booking_date: '2026-07-22',
    booking_time: '09:00:00',
    status: 'sedang_dikerjakan',
    services: [INITIAL_SERVICES[0], INITIAL_SERVICES[2]],
    complaint_notes: 'Suara rem berdecit saat hujan & indikator pengingat oli menyala.',
    created_at: '2026-07-22 08:30:00',
  },
  {
    id: 1002,
    booking_code: 'BK-20260722-002',
    user_id: 1,
    user_name: 'Dewi Lestari',
    user_phone: '081399887766',
    vehicle_id: 102,
    license_plate: 'B 5678 EFG',
    vehicle_model: 'Honda Vario 150 eSP',
    booking_date: '2026-07-22',
    booking_time: '10:00:00',
    status: 'mengantri',
    services: [INITIAL_SERVICES[0]],
    complaint_notes: 'Ganti oli rutin bulanan.',
    created_at: '2026-07-22 09:15:00',
  },
  {
    id: 1003,
    booking_code: 'BK-20260722-003',
    user_id: 3,
    user_name: 'Rudi Hermawan',
    user_phone: '085711223344',
    vehicle_id: 103,
    license_plate: 'B 8888 BOS',
    vehicle_model: 'Mitsubishi Pajero Sport 2.4',
    booking_date: '2026-07-22',
    booking_time: '08:00:00',
    status: 'selesai',
    services: [INITIAL_SERVICES[1]],
    complaint_notes: 'Tune up mesin & bersihkan CVT.',
    created_at: '2026-07-22 07:45:00',
  },
  {
    id: 1004,
    booking_code: 'BK-20260722-004',
    user_id: 4,
    user_name: 'Siti Aminah',
    user_phone: '081255443322',
    vehicle_id: 104,
    license_plate: 'B 9999 VIP',
    vehicle_model: 'Honda CR-V Turbo 1.5',
    booking_date: '2026-07-22',
    booking_time: '08:00:00',
    status: 'diambil',
    services: [INITIAL_SERVICES[0], INITIAL_SERVICES[1]],
    complaint_notes: 'Pengantian aki & servis rem.',
    created_at: '2026-07-22 07:30:00',
  },
];

export const INITIAL_WORK_ORDERS = [
  {
    id: 2001,
    work_order_number: 'WO-20260722-001',
    booking_id: 1001,
    booking_code: 'BK-20260722-001',
    license_plate: 'B 1234 XYZ',
    vehicle_model: 'Toyota Avanza Veloz 1.5 AT',
    customer_name: 'Budi Santoso',
    mechanic_id: 2,
    mechanic_name: 'Agus Pratama',
    status: 'estimate_proposed', // inspecting, estimate_proposed, in_repair, completed
    mechanic_notes: 'Hasil inspeksi: Kampas rem depan sudah sangat tipis (sisa 1.5mm) & oli mesin sudah sangat hitam. Direkomendasikan ganti kampas rem + oli Shell.',
    started_at: '2026-07-22 09:15:00',
    services: [
      { id: 1, name: 'Servis Berkala & Ganti Oli Mesin', price: 150000, approval_status: 'approved' },
      { id: 3, name: 'Servis Rem Depan & Belakang', price: 120000, approval_status: 'approved' },
    ],
    proposed_spareparts: [
      { sparepart_id: 1, name: 'Oli Mesin Shell Helix Ultra 5W-40 (1L)', qty: 4, unit_price: 165000, approval_status: 'approved' },
      { sparepart_id: 3, name: 'Kampas Rem Depan Bendix Metal King Avanza', qty: 1, unit_price: 260000, approval_status: 'proposed' }, // WAITING CUSTOMER APPROVAL
    ],
  },
];

export const INITIAL_INVOICES = [
  {
    id: 3001,
    invoice_number: 'INV-20260721-098',
    work_order_id: 1999,
    license_plate: 'B 8888 BOS',
    customer_name: 'Rudi Hermawan',
    cashier_name: 'Siti Rahmawati',
    subtotal_services: 250000,
    subtotal_spareparts: 450000,
    discount_amount: 50000,
    tax_amount: 71500, // 11% PPN
    grand_total: 721500,
    paid_amount: 750000,
    change_amount: 28500,
    payment_method: 'cash',
    payment_status: 'paid',
    paid_at: '2026-07-21 16:30:10',
  },
];
